config/routes.rb
Rails.application.routes.draw do
  root 'home#root' #redirects to '/products'

  # routes for viewing and buying products (Products Controller)
  get '/products', to: 'product#index', as: 'storefront'
  get '/products/:id/buy', to: 'product#add_to_cart', as: 'add_to_cart'
  get '/products/cart', to: 'product#view_cart', as: 'view_cart'
  get '/products/checkout', to: 'product#checkout', as: 'checkout'
  get '/products/api', to: 'product#api'
  
  # routes for viewing other public pages (Home Controller)
  get '/blog', to: 'home#blog', as: 'blog'
  get '/team', to: 'home#team', as: 'team'

  # routes for managing assets (Admin Controller)
  # --protected by HTTP Authentication--
  get '/admin', to: 'admin#index', as: 'admin_index'
  post '/admin/products', to: 'admin#create_product', as: 'create_product'
  post '/admin/blogs', to: 'admin#create_blog', as: 'create_blog'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  # protect the admin actions
  http_basic_authenticate_with name: "ew432", password: "usnausna"

  # GET /admin
  def index
    # show the form to add a new products and blogs
    @product = Product.new
    @post = Blog.new
  end

  # POST /admin/products
  def create_product
    # create a new product
    Product.create(
      name: params[:product][:name],
      description: params[:product][:description],
      quantity: params[:product][:quantity],
      price: params[:product][:price],
      image: params[:product][:image]
    )
    flash[:notice] = "Created new product"
    redirect_to :admin_index
  end
  
  # POST /admin/blog
  def create_blog
    # create a new blog post
    Blog.create(
      title: params[:blog][:name],
      content: params[:blog][:description]
    )
    flash[:notice] = "Created new blog post"
    redirect_to :admin_index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    # holds miscellaneous routes

    # GET /
    def root
        redirect_to :storefront #uses the :as parameter of the /products route
    end

    # GET /team
    def team
    end

    # GET /blog
    def blog
        @posts = Blog.all
    end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  # make sure the cart cookie is initialized
  before_action :initialize_cart

  # GET /products
  def index
    # the front page of the store
    @products = Product.all
  end

  def api
    @products = Product.all
    render json: @products and return
  end


  # POST /products/:id/buy
  def add_to_cart
    # add the selected item to the cart cookie
    session[:cart][params[:id]]+=1
    @item_count += 1
    puts session[:cart]
    flash[:notice] = "item added to cart"
    redirect_to storefront_url
  end

  # GET /products/cart
  def view_cart
    # show the shopping cart
    @items = @cart
      .filter{|id,count| count>0}
      .map{|id,count| [Product.find(id),count]}
  end

  # GET /products/checkout
  def checkout
    # this action should process the order
    # instead we are just clearing the cart :)
    session[:cart] = nil
    # update the quantity remaining
    @cart
      .filter{|id,count| count>0}
      .each do |id,count|
        p = Product.find(id)
        p.quantity = [0,p.quantity-count].max
        p.save
      end
    flash[:notice] = "Your order is on the way!"
    redirect_to storefront_url
  end

  private
  def initialize_cart
    empty_cart = Product.all.map{|p| [p.id.to_s, 0]}.to_h
    session[:cart] ||= empty_cart
    @cart = session[:cart]
    @item_count = @cart.values.reduce(:+)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/admin/index.html.erb
<h1 class="bg-warning"> Webstore Administration </h1>
<!-- flash message -->
<% if flash[:notice] %>
    <div class="alert alert-success"> <%= flash[:notice]%> </div>
<% end %>
<hr/>

<h3>New Product </h3>
<%= form_with url: :create_product, model: @product do |form| %>
    <div class="mb-3">
    <label class="form-label">Name</label>
    <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
    <label class="form-label">Description</label>
    <%= form.text_field :description, class: "form-control" %>
    </div>
    <div class="mb-3">
    <label class="form-label">Quantity</label>
    <%= form.text_field :quantity, class: "form-control" %>
    </div>
    <div class="mb-3">
    <label class="form-label">Image</label>
    <%= form.text_field :image, class: "form-control" %>
    </div>
    <div class="mb-3">
    <label class="form-label">Price</label>
    <%= form.text_field :price, class: "form-control" %>
    </div>
    
    <%= form.submit class: "btn btn-primary" %>
<% end %>
<hr/>
<h3 class="mt-4">New Blog Post </h3>

<%= form_with url: :create_blog, model: @post do |form| %>
    <div class="mb-3">
    <label class="form-label">Title</label>
    <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="mb-3">
    <label class="form-label">Content</label>
    <%= form.text_area :content, rows: "3", class: "form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/home/blog.html.erb
<h1 class="display-3"> My AI Powered Blog :)</h1>
<hr/>
<% @posts.each do |post| %>
<p class="display-6">
<%= post.title %>
</p>
<p style="white-space: pre-wrap">
<%= post.content %>
</p>
<% end %>

app/views/home/team.html.erb
Team!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- bootstrap assets -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class="container">
    <!-- navbar -->
    <nav class="navbar  navbar-expand-lg navbar-light bg-light border-bottom border-dark border-1">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <%= image_tag("wrc.png", width: "30", class: "d-inline-block align-bottom")%> 
          <!-- page title -->
          EW432 Store
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <!-- navbar links -->
            <%= link_to "Blog", "/blog", class: "nav-link" %>
            <%= link_to "Team", "/team", class: "nav-link" %>
            <%= link_to "Admin", "/admin", class: "nav-link" %>
        </div>
      </div>        
    </nav>
  
    <!-- page content -->
    <div>
      <%= yield %>
    </div> 
  
  </body>
</html>

app/views/product/index.html.erb
<!-- cart banner -->
<% if @item_count >0%>
  <div class="alert alert-primary">
    You have <%=pluralize(@item_count,"item")%> in your cart &mdash; <%= link_to "Checkout", view_cart_path %>
  </div>
<% end %>

<!-- flash message -->
<% if flash[:notice] %>
    <div class="alert alert-success"> <%= flash[:notice]%> </div>
<% end %>

<!-- product listing -->
<div class="row">
<% @products.each do |product| %>
<div class="card m-2" style="width: 18rem; background-color: #efe4b07a">
  <!-- product image -->
  <%= image_tag product.image, class: "card-img-top rounded mt-2" %>
  <!-- quantity available -->
  <% if product.quantity == 0 %>
    <span class="badge bg-danger">sold out</span>
  <% elsif product.quantity < 3 %>
    <span class="badge bg-warning">only <%= product.quantity %> left! </span>
  <% else %>
    <span class="badge bg-secondary"><%= product.quantity %> available </span>
  <% end %>
  <!-- title, price, and description -->
  <div class="card-body">
    <h5 class="card-title"><%= product.name%>: <%=number_to_currency product.price%></h5>
    <p class="card-text"><%= product.description%></p>
    <!-- buy button -->
    <% if product.quantity > 0 %>
      <%= link_to "Add To Cart", add_to_cart_path(product), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>
</div>

app/views/product/view_cart.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
    <h2>There is nothing in your cart!</h2>
<% else %>

<ul>
<% @items.each do |product, count| %>
    <li><%= pluralize(count, product.name) %></li>
<% end %>
</ul>
<%=link_to "Checkout", checkout_path, class: "btn btn-primary"%>
<% end %>
<hr/>
<%=link_to "Keep Shopping", root_path %>